language: python
python:
    - "2.7"
    - "3.3"
    - "pypy"
install:
    - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install PyCrypto==2.3; fi"
    - "pip install -r requirements.txt --use-mirrors"
before_script:
    - "pip install python-coveralls coverage"
script:
    - "coverage run runtests.py"
after_success:
    - "coveralls"
notifications:
    email: false
